FROM my-nginx

COPY urisemic.nginx.conf.d /etc/nginx/conf.d/default.conf
COPY urisemic.nginx.conf /etc/nginx/nginx.conf
COPY urisemic.mime.types /etc/nginx/mime.types
RUN mkdir -p /etc/nginx/lua
COPY urisemic.lua /etc/nginx/lua/
COPY htmlmap.lua /etc/nginx/lua/
COPY robots.txt /usr/share/nginx/html/
