version: "3.7"

services:
  tls-terminator:
    environment:
      APP_SERVER1: http://proxy
      DOMAIN1: uri.semic.eu
      EMAIL1: bert.van.nuffelen@tenforce.com
      APP_SERVER2: http://proxy
      DOMAIN2: wikibase.semic.eu
      EMAIL1: bert.van.nuffelen@tenforce.com
    image: cad
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./semic.Caddyfile:/etc/caddy/Caddyfile
      - /etc/caddy/data:/data
  uriproxy:
    image: ng
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "82:80"
    command: [nginx-debug, '-g', 'daemon off;']
